### PR TITLE
Make spec [soft,hard]ware agnostic

### PR DESCRIPTION
**Pull request by damosvil**
Replaced ESC demag metric by stress leven to make the spec [soft,hard]ware agnostic. Demag metric is terminology related to Blheli derivatives, AM32 and others may not use this terminology at all

### CODE REVIEW

**Comment by stylesuxx** [comment]
Maybe the explanation for stress level could be added to the glossary section?

**Comment by damosvil** [comment]
@stylesuxx Added stress level explanation to glosary

**Comment by damosvil** [comment]
Updated events wording

**Comment by damosvil** [comment]
@stylesuxx  Sorry, review request was a wrong clic

**Pull request merged**
